const artikel = [
  {
    'id': '636e5a5fba0f486fa1445327',
    'title': 'Updated: 5 Olahraga untuk Ibu Hamil',
    'slug': '5-olahraga-untuk-ibu-hamil',
    'category': 'Kehamilan',
    'img': 'https://lh6.googleusercontent.com/LR3IsdrZxLkDVR5a1pt2s5w6m-PPSPYCqsDayGU1BjDkZyeb0FMYEg4fM9_5TaTicVw=w2400',
    'source': 'halodoc.com',
    'overview': 'Halodoc. “Ibu hamil juga perlu melakukan olahraga agar kesehatan tetap terjaga dengan baik. Ada berbagai jenis olahraga untuk ibu hamil, seperti be...',
  },
  {
    'id': '636e5a5f87ds8f687s8d9d8d',
    'title': 'Tips Olahraga Aman saat Puasa, Mending Habis Sahur atau Sebelum Buka?',
    'slug': 'Tips-Olahraga-Aman-saat-Puasa,-Mending-Habis-Sahur-atau-Sebelum-Buka?',
    'category': 'Kebugaran',
    'img': 'https://akcdn.detik.net.id/community/media/visual/2023/03/22/1268399964_169.jpeg?w=700&q=90',
    'source': 'health.detik.com',
    'overview': 'Detikhealth. Puasa tidak seharusnya menjadi alasan untuk malas berolahraga. Pasalnya, be...',
  },
  {
    'id': 'asd89f7as89df7as89d7f89as',
    'title': 'Yuk Tetap Sehat Bebas Anemia',
    'slug': 'Yuk-Tetap-Sehat-Bebas-Anemia',
    'category': 'Umum',
    'img': 'https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-content/uploads/2021/06/16070755/Anemia.jpg',
    'source': 'health.detik.com',
    'overview': 'Bio Farma. Anemia adalah kondisi ketika tubuh kekurangan sel darah merah...',
  },
  {
    'id': 'as8d7f98a7s8d7f9a78sd9f8',
    'title': '12 Manfaat Bersepeda untuk Kesehatan, Bisa Mengurangi Stres Lho',
    'slug': '12-Manfaat-Bersepeda-untuk-Kesehatan-Bisa-Mengurangi-Stres-Lho',
    'category': 'Kebugaran',
    'img': 'https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-content/uploads/2021/10/18011104/Bukan-Cuma-Menyehatkan-Jantung-Ini-X-Manfaat-Bersepeda-01.jpg',
    'source': 'health.detik.com',
    'overview': 'Detikhealth. Bersepeda adalah aktivitas yang menyenangkan dan memiliki banyak...',
  },
  {
    'id': '89as7d98f7as8d9f78asd9f87',
    'title': 'Cukup 30 Menit Sehari, Lari Pagi Bisa Sehatkan Otot, Tulang, Jantung',
    'slug': 'Cukup-30-Menit-Sehari-Lari-Pagi-Bisa-Sehatkan-Otot-Tulang-Jantung',
    'category': 'Kebugaran',
    'img': 'https://cdnwpedutorenews.gramedia.net/wp-content/uploads/2021/03/02135350/pengertian-lari-pendek-min-810x555.jpg',
    'source': 'health.detik.com',
    'overview': 'Detikhealth. Lari pagi adalah kegiatan yang bermanfaat untuk kesehatan tubuh. Dengan...',
  },
  {
    'id': '8as7df8a79s8df7as89d8a79s',
    'title': 'Kompres untuk Demam dengan Air Panas atau Dingin, Efektif?',
    'slug': 'Kompres-untuk-Demam-dengan-Air-Panas-atau-Dingin-Efektif',
    'category': 'Kebugaran',
    'img': 'https://asset.kompas.com/crops/PDA8rdw8kPepotoZWez_4YylksQ=/0x0:1000x667/750x500/data/photo/2022/02/25/6218fc0c9185c.jpg',
    'source': 'health.detik.com',
    'overview': 'Detikhealth. Ketika demam, kompres dapat membantu mengurangi suhu tubuh. Namun, pertanyaan yang...',
  },
  {
    'id': '876as87d9f8a7sd9f8a7d9f8',
    'title': 'Inilah 4 Skill Pertolongan Pertama yang Wajib Dikuasai',
    'slug': 'Inilah-4-Skill-Pertolongan-Pertama-yang-Wajib-Dikuasai',
    'category': 'Kebugaran',
    'img': 'https://www.pelatihansertifikasi.com/image/2018-10-first-aid-660x405.jpg',
    'source': 'health.detik.com',
    'overview': 'Detikhealth. Kejadian darurat bisa terjadi kapan saja dan di mana saja. Oleh karena...',
  },
  {
    'id': 'asd8f7a98sd7f89as7d89f89s',
    'title': 'Morning Sickness: Penyebab, Gejala, dan Cara Mengatasinya',
    'slug': 'Morning-Sickness-Adalah-Penyebab-Gejala-dan-Cara-Mengatasinya',
    'category': 'Kebugaran',
    'img': 'https://www.arabnews.com/sites/default/files/styles/n_670_395/public/2019/10/02/1779216-1902343925.jpg?itok=tKLQK_X8',
    'source': 'health.detik.com',
    'overview': 'Detikhealth. Morning sickness atau mual-mual di pagi hari adalah gejala umum...',
  },
];

module.exports = artikel;
